version: "3.9"

services:
  app:
    build: .
    image: studentblog-app:latest
    container_name: app_blogging
    restart: always
    ports:
      - "${APP_PORT}:3000"
    environment:
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@database:5432/${DB_DATABASE}"
    depends_on:
      - database
    volumes:
      - .:/app
      - /app/node_modules
  database:
    image: postgres
    container_name: database_blogging
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local