# Use a imagem oficial do Node.js como base
FROM node:14

# Defina o diretório de trabalho
WORKDIR /usr/src/app

# Copie o package.json e package-lock.json
COPY package*.json ./

# Instale as dependências
RUN npm install

# Copie o restante do código da aplicação
COPY . .

# Instale as dependências de desenvolvimento
RUN npm install typescript ts-node ts-node-dev @types/node @types/express @types/bcrypt @types/jwt-simple -D

# Compile o código TypeScript
RUN npm run build

# Exponha a porta da aplicação
EXPOSE 3000

# Comando para iniciar a aplicação no ambiente de desenvolvimento
CMD ["npm", "run", "dev"]